# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
%run initialise.py

ModuleNotFoundError: No module named 'nbformat'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "cc",
      "args": "-fno-strict-aliasing, -DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64",
      "linker args": "-fno-strict-aliasing, -DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "c++",
      "args": "-DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64",
      "linker args": "-DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "

/Users/yoadoxman/Documents/ Weizmann/ML Course 2023/numpy-100/.venv/lib/python3.12/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [15]:

v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [17]:
memoryUse = v.nbytes
print(memoryUse)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [19]:
v = np.zeros(10)
v[4] =1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [29]:
w = np.linspace(10,49,40)
print(w)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [30]:
w = w[::-1]
print(w)

[49. 48. 47. 46. 45. 44. 43. 42. 41. 40. 39. 38. 37. 36. 35. 34. 33. 32.
 31. 30. 29. 28. 27. 26. 25. 24. 23. 22. 21. 20. 19. 18. 17. 16. 15. 14.
 13. 12. 11. 10.]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [31]:
M = np.linspace(0,8,9).reshape(3,3)
print(M)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [41]:

array = [1, 2, 0, 0, 4, 0]
ind = np.nonzero(array)
print(np.array(array)[ind[0]])


[1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [42]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [46]:
M = np.random.rand(3,3,3)
print(M)

[[[0.22372185 0.4853905  0.74225041]
  [0.46357448 0.1785684  0.07442274]
  [0.61944466 0.04177086 0.19770079]]

 [[0.47473298 0.02566719 0.297084  ]
  [0.97063942 0.26142435 0.85922778]
  [0.51820558 0.30512358 0.20322712]]

 [[0.73458322 0.21226643 0.35325162]
  [0.23205465 0.05132016 0.48423175]
  [0.08306405 0.56656795 0.68927489]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [53]:
M = np.random.randn(10,10)
K = np.amax(M)
L = np.amin(M)
print(M,K,L)

[[-0.37217931  1.32418058 -2.33107049  0.88385727  0.21855147 -0.18270781
  -0.3854042   0.12525477 -0.74544497  0.4288906 ]
 [ 0.41005127  0.42376957 -2.05524167 -0.12286762  0.5713925  -1.6803605
  -0.10268995  0.31044377 -0.96923813 -0.67220705]
 [ 1.18405881 -1.57840144 -0.51536457 -1.50428588 -1.04502161 -0.57269952
  -1.6261955   1.52903025 -0.39449056 -0.51799919]
 [ 0.43874365 -0.33194843 -0.84249431  1.69429417 -1.20814044  1.69753305
   0.34532811 -0.01032085  0.34254416 -0.224874  ]
 [ 0.11791339  0.42847438 -1.65322475 -0.09443648  2.73227572  0.48471564
  -0.36782317 -0.56073524  0.58178814 -0.27805452]
 [-0.13525173  0.75972424 -0.17692831  0.92358562  0.74853649  0.50638655
  -0.96722083  1.79449969 -0.20405222 -1.00971638]
 [ 0.01693719  0.26255273 -0.33467305  1.66931686  1.30650928  1.57242865
   0.00346192  0.97974357  0.14626929  0.10454883]
 [ 0.28095726 -0.3127649   0.85532997  1.45267734  2.18030656 -0.0600824
  -1.49235065 -1.30670978  1.37220725  0.72295799]
 [

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [57]:
x = np.random.rand(30)*12
a = np.mean(x)
print(x,a)

[ 9.31772688  5.04325989  1.07637019  6.09302322  7.10744977  6.29568643
  9.78655273  2.86658677  1.22036338  0.23753946  2.46051286  8.4665875
  5.25728167  7.29162192  3.74069862  1.83914301  4.8891999  10.7890361
  4.31948375 10.4555726   0.44332855  7.00437812  0.93604793  1.1593087
  3.21172004  4.28182607  5.67892959  5.14716082  9.11074636  8.83630739] 5.145448340738546


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [77]:
x = np.zeros(100).reshape(10,10)
x[:1] = np.ones(10)
x[-1:] = np.ones(10)
x[:, 0] = np.ones(10)
x[:, -1] = np.ones(10)
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [4]:
x = (np.random.rand(10)*12).reshape(5,2)
print(x)
x = np.pad(x,((1,),(1,)),'constant', constant_values=(0,))
print(x)

[[ 2.23481321  5.590511  ]
 [10.40320259  0.18790417]
 [ 1.50919547  6.01732952]
 [ 5.22113715 10.57048666]
 [ 7.78725087  5.55447598]]
[[ 0.          0.          0.          0.        ]
 [ 0.          2.23481321  5.590511    0.        ]
 [ 0.         10.40320259  0.18790417  0.        ]
 [ 0.          1.50919547  6.01732952  0.        ]
 [ 0.          5.22113715 10.57048666  0.        ]
 [ 0.          7.78725087  5.55447598  0.        ]
 [ 0.          0.          0.          0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [11]:

0.3 == 3*0.1 #is false because of floating point arythmetics

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
M = np.random.random((5,5))
for i in range(4):
    M[i+1,i] = i+1
print(M)

A = np.arange(4) +1 
C = np.diag(A,-1) #-1 - one diagonal lower
print(C)


[[0.90496338 0.53077687 0.28975342 0.95845668 0.09858079]
 [1.         0.69923475 0.10029593 0.10160822 0.50761192]
 [0.2331372  2.         0.6086334  0.12951432 0.14008073]
 [0.62725136 0.40706788 3.         0.66901553 0.22588697]
 [0.95332749 0.70275355 0.31830934 4.         0.02905351]]
[[0.65108289 0.8711833  0.3050186  0.59806306 0.72795803]
 [1.33001858 0.23360831 0.08232633 0.61254701 0.31697029]
 [0.3736857  2.98845809 0.60449837 0.46747505 0.82837295]
 [0.91186824 0.55827189 3.28130741 0.89085693 0.53244098]
 [0.0484728  0.70783327 0.88328743 4.98209361 0.18307198]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [34]:
M = np.zeros((8,8))
# M[::2] = 1 #all rows, all columns, jump rows by 2 every time
M[::2, ::2] = 1
M[1::2, 1::2] = 1
print(M) 


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [47]:
A = np.zeros((6,7,8))
A = A.astype(int)
e = np.unravel_index(99,A.shape)
print(e)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [51]:
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)
print(a.shape)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
(8, 8)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [52]:
A = np.random.random((5,5))
print(A)
A = A/(np.linalg.norm(A))
print(A)

[[0.83914027 0.46669901 0.10334517 0.26292293 0.29145527]
 [0.86484766 0.9947623  0.871279   0.50833517 0.446005  ]
 [0.73749122 0.44336698 0.96783008 0.16457346 0.1146757 ]
 [0.517829   0.4951333  0.42614707 0.38491971 0.98345099]
 [0.86501641 0.6371987  0.39907114 0.02316174 0.20702872]]
[[0.28088218 0.15621636 0.03459233 0.08800718 0.0975577 ]
 [0.28948711 0.33297294 0.29163985 0.17015307 0.14928953]
 [0.24685759 0.14840652 0.32395802 0.05508704 0.03838495]
 [0.1733309  0.16573406 0.14264256 0.12884269 0.32918675]
 [0.2895436  0.21328706 0.13357954 0.00775284 0.06929792]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [58]:
color = np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])
#can i do it using the shortcut name of np.ubyte?
colorbutbetter = {
            "names":["r", "g", "b", "a"],
            "values": [np.ubyte, np.ubyte, np.ubyte, np.ubyte]
            } 
somecolorarray = np.array([(20,5,7,10),(0,1,2,3),(23,34,45,56)],dtype=color)

[(20,  5,  7, 10) ( 0,  1,  2,  3) (23, 34, 45, 56)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [66]:
A = np.random.random((5,3))
B = np.random.random((3,2))
C = np.matmul(A,B)
print(C)

[[0.25289193 0.82327093]
 [0.37611882 0.39136638]
 [0.60937908 0.35848266]
 [1.02141061 0.77916577]
 [0.66401859 1.1340251 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [69]:
a = np.linspace(1,10,20)
a[(a>3) & (a<8)] = a[(a>3) & (a<8)]*(-1)
# could be a[(a>3) & (a<8)] *= -1
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684 -3.36842105
 -3.84210526 -4.31578947 -4.78947368 -5.26315789 -5.73684211 -6.21052632
 -6.68421053 -7.15789474 -7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [76]:
#### 26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) 

#it's 9 and then 10, why? because the last line is actually np.sum(what we sum over, axis) 

10
10


NameError: name 'numpy' is not defined

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [5]:
Z = np.array([1,2,3],dtype = int)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# Z<Z>Z is false

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [12]:
#### 28. What are the result of the following expressions? (★☆☆)
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/3c/459yj7ps3tsgjgp6229g7hhr0000gn/T/ipykernel_43829/2616014464.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/3c/459yj7ps3tsgjgp6229g7hhr0000gn/T/ipykernel_43829/2616014464.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/3c/459yj7ps3tsgjgp6229g7hhr0000gn/T/ipykernel_43829/2616014464.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [14]:
# you need to round float to its closest integer
x = np.random.uniform(10,20,10)
print(x)
y = np.round(x)
print(y)    
x = np.copysign(np.round(abs(x)),x)
print(x) 

[12.34802707 19.72280249 17.43077214 19.02801959 14.75168922 11.19219331
 12.35546766 14.3908904  16.16425331 16.32883975]
[12. 20. 17. 19. 15. 11. 12. 14. 16. 16.]
[12. 20. 17. 19. 15. 11. 12. 14. 16. 16.]


#### 30. How to find common values between two arrays? (★☆☆)

In [18]:
x = np.random.uniform(10,20,10)
y = x+np.tile([0,1],5)
a = x[x == y]
b = np.intersect1d(x,y)
print(a)
print(b)

[13.9928664  12.29275672 16.80839893 17.29753005 13.82384914]
[12.29275672 13.82384914 13.9928664  16.80839893 17.29753005]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [4]:
np.sqrt(-1) == np.emath.sqrt(-1) #NaN vs. complex number

/var/folders/3c/459yj7ps3tsgjgp6229g7hhr0000gn/T/ipykernel_15435/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [14]:
print(np.datetime64('today','D'))
print(np.datetime64('today','D') + np.timedelta64(1,'D'))
print(np.datetime64('today','D') - np.timedelta64(1,'D'))



2024-03-03
2024-03-04
2024-03-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [16]:
print(print(np.arange('2016-07','2016-08',dtype = 'datetime64[D]')))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
None


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
#NVM

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [26]:
a = np.random.random(10)*26
print(a)
b = a.round()
print(b)
# c = np.ceil(a)
# print(c)
d = a//1
print(d)
e = a - a%1
print(e)
f = a.astype(int)
print(f)

[18.68276701 18.38026413  7.72180139  8.33230313 20.17726763 15.81246735
  6.2357875   7.60542841 15.98956381 20.65977278]
[19. 18.  8.  8. 20. 16.  6.  8. 16. 21.]
[19. 19.  8.  9. 21. 16.  7.  8. 16. 21.]
[18. 18.  7.  8. 20. 15.  6.  7. 15. 20.]
[18. 18.  7.  8. 20. 15.  6.  7. 15. 20.]
[18 18  7  8 20 15  6  7 15 20]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [27]:
A = np.tile(np.arange(5),(5,1))
print(A)
# what is broadcasting?

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [41]:
def gen():
    for _ in range(10):
        yield np.random.randint(100,200)
      

x = np.fromiter(gen(),dtype =(int,1),count = -1)
print(x)


[156 127 187 111 167 147 178 156 121 117]


/var/folders/3c/459yj7ps3tsgjgp6229g7hhr0000gn/T/ipykernel_15435/2009878960.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.fromiter(gen(),dtype =(int,1),count = -1)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [45]:
z = np.linspace(0,1,11, endpoint=False)
print(z[1:])
#cant it be done in a more pretty fashion?

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
#nvm

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [46]:
z = np.arange(100)
print(np.add.reduce(z))

4950


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
#nvm

#### 43. Make an array immutable (read-only) (★★☆)

In [47]:
a = np.arange(11)
a.flags.writeable = False
# a[0] = 221

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [67]:
a = np.random.randn(20).reshape(10,2)
print(a)
x,y = a[:,0],a[:,1]
# print(f"hey hey{x}")
b = np.array([np.absolute(x+1j*y),np.angle(x+1j*y)])
print(b)
#sanity check:
l,m = a[:,0], a[:,1]
R = np.sqrt(l**2+m**2)
T = np.arctan2(m,l)
diff = b-[R,T]
print(diff)

[[ 1.14839322 -0.0136331 ]
 [ 0.36354217 -0.05763569]
 [-0.35723368  0.18252055]
 [-2.2489762   1.20059944]
 [ 0.77440205  1.98045396]
 [-0.79923905  1.50537873]
 [ 0.03917471 -0.33298857]
 [ 0.86530537 -2.74760116]
 [-2.56296588  0.64818373]
 [ 0.93721666  0.96138863]]
[[ 1.14847414  0.36808257  0.40116039  2.54937894  2.12647511  1.70439085
   0.33528502  2.88063631  2.64365963  1.34262547]
 [-0.0118709  -0.15723062  2.66924122  2.65123888  1.19805306  2.05887463
  -1.45368881 -1.26569808  2.8938829   0.79812891]]
[[ 0.00000000e+00 -5.55111512e-17 -5.55111512e-17  0.00000000e+00
   0.00000000e+00 -2.22044605e-16  0.00000000e+00  4.44089210e-16
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [70]:
A = np.random.random(10)
print(A)
A[np.argmax(A)] = 0
print(A)


[0.93852914 0.36755729 0.864156   0.72097707 0.3774627  0.26731478
 0.98681893 0.67915269 0.24945898 0.02208333]
[0.93852914 0.36755729 0.864156   0.72097707 0.3774627  0.26731478
 0.         0.67915269 0.24945898 0.02208333]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [79]:
a = np.zeros((3,3),[('x',float),('y',float)])
a['x'] = np.linspace(0,1,3)
a['y'] = np.linspace(0,1,3)
print(np.shape(a))

Z = np.zeros((3,3), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,3),
                             np.linspace(0,1,3))
print(np.shape(Z))

(3, 3)
(3, 3)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [81]:
x = np.random.randn(2)
y = np.random.randn(3)
C = 1/np.subtract.outer(x,y)
print(C)

[[ 0.56804652 -0.87623768  2.67091125]
 [ 2.20318081 -0.40853464 -1.07281642]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [99]:
x = np.tile(np.array([0,12,3,12,12,12]),23)
print(np.argmax(np.bincount(x)))

_,z = np.unique(x,return_index=True)
print(x[z[-1]])
# I thought you were supposed to find the most ocurring value of a given array


12
12


#### 49. How to print all the values of an array? (★★☆)

In [100]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [111]:
x = np.random.rand(7)*10
t = np.random.randn()
y = x[np.argmax(np.absolute(x-t))]
w = sorted(x,reverse=True,key = lambda q: (q-t)**2)
print(x,t,y)
print(f'the first value in the sorted version is {w[0]}')


[5.18753152 4.89204774 2.13121389 2.95910245 4.50396589 7.92132466
 1.56174727] -0.3262593934740482 7.921324663888237
the first value in the sorted version is 7.921324663888237


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [117]:
z = np.zeros(3,[('position',[('x',float),('y',float) ]),('color',[('r',float),('g',float),('b',float) ])])
z[0]=((1,2),(3,4,9))
z[1] = 1
print(z)

[((1., 2.), (3., 4., 9.)) ((1., 1.), (1., 1., 1.))
 ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
#nvm


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [122]:
a = np.random.randn(10).astype(np.float32)
y = a.view(np.int32)
a = y[:] 
#Without this line, the a array would still be a view of the same memory as the y array,
 #and any changes made to one array would affect the other array.
print(a,y)

[ 1070956120 -1088610107 -1085333777 -1096384435 -1085137247 -1077865225
  1069206039 -1103873261 -1080843203 -1081459851] [ 1070956120 -1088610107 -1085333777 -1096384435 -1085137247 -1077865225
  1069206039 -1103873261 -1080843203 -1081459851]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [130]:
from io import StringIO
file = StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')
x = np.genfromtxt(file,delimiter=',',dtype=float)
print(x)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
#nvm

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [134]:
import math
x , y = np.meshgrid(np.linspace(-1,1,4),np.linspace(-1,1,4))
sigma , mu = 1. , 0.
Gaussian2D = np.exp((-(x-mu)**2-(y-mu)**2)/(2*sigma**2))/(2*math.pi*sigma**2)**0.5
print(Gaussian2D)

[[0.14676266 0.2288945  0.2288945  0.14676266]
 [0.2288945  0.35698924 0.35698924 0.2288945 ]
 [0.2288945  0.35698924 0.35698924 0.2288945 ]
 [0.14676266 0.2288945  0.2288945  0.14676266]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [148]:
x = np.arange(10)
p = np.random.randint(0,9)
np.put(x,np.random.choice(range(10),p,replace=False),1)
print(x)

[1 1 2 1 1 1 1 1 1 9]


#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [157]:
a = np.random.randn(1,3)
b = np.transpose(a)
c = a[:,np.newaxis]+b
print(c)
#idk doesnt matter right now

[[[-2.78691174 -2.94973231 -2.48561493]
  [-2.94973231 -3.11255289 -2.64843551]
  [-2.48561493 -2.64843551 -2.18431812]]]


#### 63. Create an array class that has a name attribute (★★☆)

In [165]:
class ArrayWithName(np.ndarray):
    
    def __new__(cls,array,name='shmulik'): #this creates a new instance of the ArrayWithName class
        obj = np.asarray(array).view(cls) #the view(cls) specifies what is obj's type. Ron let's talk about it
        obj.name = name
        return obj
    
    def __ArrayFixer__(self,obj):
        if obj is None:
            return 
        self.name = getattr(obj,'name',None)

ari = ArrayWithName([1,2,3])
print(ari.name)



shmulik


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
#nvm

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [189]:
np.linalg.matrix_rank(np.random.randint(0,2,(3,3)))

2

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [186]:
x=np.array([1,2,3], dtype=[('x', '<f8'), ('y', '<i8')])
x = x.view(np.recarray)
x.x
x.y
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

array([1, 2, 3])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [182]:
import scipy
from scipy import stats
X = np.random.rand(100)
M = np.mean(X)
N = 1000
num_of_reps = 300
res = np.zeros(num_of_reps)
for i in range(num_of_reps):
    sample = np.random.choice(X,N)
    res[i] = sample.mean()
print(f'the 95% percentile is {np.percentile(res,[2.5,97.5])} and the real mean is {M}')
print()
#could i do it any better? 

the 95% percentile is [0.48336308 0.51519822] and the real mean is 0.49896328283074476

